Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-05, with the labels that each got.

#409 Add apt-get update command to the travis script
  .travis.yml
Labels: ready

#399 Manifold Learning Visualization
  docs/api/features/images/concrete_isomap_manifold.png
  docs/api/features/images/concrete_lle_manifold.png
  docs/api/features/images/concrete_modified_manifold.png
  docs/api/features/images/concrete_spectral_manifold.png
  docs/api/features/images/concrete_tsne_manifold.png
  docs/api/features/images/occupancy_isomap_manifold.png
  docs/api/features/images/occupancy_lle_manifold.png
  docs/api/features/images/occupancy_modified_manifold.png
  docs/api/features/images/occupancy_select_k_best_isomap_manifold.png
  docs/api/features/images/occupancy_spectral_manifold.png
  docs/api/features/images/occupancy_tsne_manifold.png
  docs/api/features/images/s_curve_hessian_manifold.png
  docs/api/features/images/s_curve_isomap_manifold.png
  docs/api/features/images/s_curve_lle_manifold.png
  docs/api/features/images/s_curve_ltsa_manifold.png
  docs/api/features/images/s_curve_mds_manifold.png
  docs/api/features/images/s_curve_modified_manifold.png
  docs/api/features/images/s_curve_spectral_manifold.png
  docs/api/features/images/s_curve_tsne_manifold.png
  docs/api/features/index.rst
  docs/api/features/manifold.py
  docs/api/features/manifold.rst
  docs/index.rst
  tests/baseline_images/test_features/test_manifold/test_manifold_classification.png
  tests/baseline_images/test_features/test_manifold/test_manifold_pandas.png
  tests/baseline_images/test_features/test_manifold/test_manifold_regression.png
  tests/baseline_images/test_features/test_manifold/test_manifold_single.png
  tests/test_features/test_manifold.py
  yellowbrick/features/manifold.py
Labels: level: intermediate, review, type: feature

#445 Update tutorial.rst
  docs/tutorial.rst
Labels: ready

#427 Add alpha transparency to RadViz #419
  yellowbrick/features/radviz.py
Labels: in progress
