Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-12, with the labels that each got.

#661 Update default ranking algorithm in Rank2D docs
  docs/api/features/rankd.rst
Labels: review

#671 Reinstate mpl 3
  docs/requirements.txt
  requirements.txt
  tests/requirements.txt
Labels: ready

#670 Added code review checklist
  docs/contributing.rst
  docs/contributing/advanced_development_topics.rst
  docs/contributing/developing_visualizers.rst
  docs/contributing/getting_started.rst
  docs/contributing/index.rst
  docs/index.rst
Labels: review

#674 Adds test for DispersionPlot quickmethod with Image Comparison
  tests/baseline_images/test_text/test_dispersion/test_quick_method.png
  tests/test_text/test_dispersion.py
Labels: review

#673 Docs headings
  docs/api/classifier/confusion_matrix.rst
  docs/api/classifier/rocauc.rst
  docs/api/contrib/missing/bar.rst
  docs/api/contrib/missing/dispersion.rst
  docs/api/model_selection/cross_validation.rst
Labels: review, type: documentation

#667 Wrote a UMAPVisualizer for text
  docs/api/text/images/umap_all_docs_cosine.png
  docs/api/text/images/umap_all_docs_euclidean.png
  docs/api/text/images/umap_kmeans.png
  docs/api/text/images/umap_no_labels.png
  docs/api/text/index.rst
  docs/api/text/umap_vis.py
  docs/api/text/umap_vis.rst
  requirements.txt
  tests/baseline_images/test_text/test_umap/test_integrated_umap.png
  tests/baseline_images/test_text/test_umap/test_make_classification_umap.png
  tests/baseline_images/test_text/test_umap/test_make_classification_umap_class_labels.png
  tests/baseline_images/test_text/test_umap/test_no_target_umap.png
  tests/baseline_images/test_text/test_umap/test_visualizer_with_pandas.png
  tests/requirements.txt
  tests/test_text/test_umap.py
  yellowbrick/text/__init__.py
  yellowbrick/text/umap_vis.py
Labels: ready

#672 Adds changelog information for recent PRs
  docs/changelog.rst
  docs/contributing/index.rst
Labels: review

#678 Extend FeatureImportances docs/tests for stacked importances
  docs/api/features/images/feature_importances_stacked.png
  docs/api/features/importances.py
  docs/api/features/importances.rst
  docs/api/text/umap_vis.rst
  docs/changelog.rst
  tests/baseline_images/test_features/test_importances/test_multi_coefs_stacked.png
  tests/test_features/test_importances.py
  yellowbrick/features/importances.py
Labels: review

#676 Detect continuous vs discrete target for color utils.
  tests/test_utils/test_target.py
  yellowbrick/utils/target.py
Labels: review
