Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-09, with the labels that each got.

#592 Color DispersionPlot markers based on target values
  examples/rebeccabilbro/dispersion_plots.ipynb
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_color_words_by_class.png
  tests/test_text/test_dispersion.py
  yellowbrick/text/dispersion.py
Labels: review

#595 Removed Override of Poof Method in JointPlot
  tests/baseline_images/test_features/test_jointplot/test_jointplot_has_no_errors.png
  tests/baseline_images/test_features/test_jointplot/test_jointplot_integrated_has_no_errors.png
  tests/test_features/test_jointplot.py
  yellowbrick/features/jointplot.py
Labels: ready

#603 Add new target module to the documentation's index
  docs/api/target/binning.py
  docs/api/target/binning.rst
  docs/api/target/images/balanced_binning_reference.png
  docs/api/target/index.rst
  docs/gallery.rst
  docs/index.rst
  examples/rebeccabilbro/balanced_binning_docs.ipynb
  yellowbrick/target/binning.py
Labels: review, type: documentation

#608 Bugfix to prevent wrong percent points showing up in ConfusionMatrix
  examples/rebeccabilbro/correcting_percents_confusion_matrix.ipynb
  tests/baseline_images/test_classifier/test_confusion_matrix/test_class_filter_eg_zoom_in.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_confusion_matrix.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_extra_classes.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_fontsize.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_inverse_mapping.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_no_classes_provided.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_one_class.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_pandas_integration.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_percent_mode.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_quick_method.png
  yellowbrick/classifier/confusion_matrix.py
Labels: ready

#617 Adding color selection to ResidualsPlot() histogram
  tests/test_text/test_freqdist.py
  yellowbrick/regressor/residuals.py
Labels: ready

#612 Update examples notebook
  examples/examples.ipynb
Labels: review
