Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-07, with the labels that each got.

#494 Link Dispersion Plot from index and README
  DESCRIPTION.rst
  README.md
  docs/api/text/dispersion.rst
  docs/index.rst
Labels: review

#407 WIP ClassificationScoreVisualizers should return accuracy
  yellowbrick/classifier/base.py
Labels: ready

#505 Fixes Manifold fit_transform bug.
  tests/test_features/test_manifold.py
  yellowbrick/features/manifold.py
Labels: review

#503 Follow-up on classification score visualizers
  tests/test_classifier/test_class_balance.py
  tests/test_classifier/test_class_prediction_error.py
  tests/test_classifier/test_classification_report.py
  tests/test_classifier/test_confusion_matrix.py
  tests/test_classifier/test_rocauc.py
  yellowbrick/classifier/class_balance.py
  yellowbrick/classifier/classification_report.py
  yellowbrick/classifier/confusion_matrix.py
  yellowbrick/classifier/rocauc.py
Labels: review

#493 Add Timer utility and update Manifold fit time
  examples/examples.ipynb
  tests/test_utils/test_timer.py
  yellowbrick/features/manifold.py
  yellowbrick/utils/timer.py
Labels: ready

#517 Add Examples Notebook of Regression Visualizers (#470)
  examples/regression-examples.ipynb
Labels: review

#519 Adding MissingValues to Contrib
  docs/api/contrib/index.rst
  docs/api/contrib/missing/bar.py
  docs/api/contrib/missing/bar.rst
  docs/api/contrib/missing/dispersion.py
  docs/api/contrib/missing/dispersion.rst
  docs/api/contrib/missing/images/missingbar.png
  docs/api/contrib/missing/images/missingbar_with_targets.png
  docs/api/contrib/missing/images/missingdispersion.png
  docs/api/contrib/missing/images/missingdispersion_with_targets.png
  docs/api/contrib/missing/index.rst
  examples/ndanielsen/Missing Values Examples.ipynb
  examples/ndanielsen/Missing Values.ipynb
  examples/ndanielsen/Untitled.ipynb
  examples/ndanielsen/Untitled1.ipynb
  examples/ndanielsen/horse-colic.attrs
  tests/baseline_images/test_contrib/test_missing/test_bar/test_missingvaluesbar_numpy.png
  tests/baseline_images/test_contrib/test_missing/test_bar/test_missingvaluesbar_numpy_with_y_target.png
  tests/baseline_images/test_contrib/test_missing/test_bar/test_missingvaluesbar_numpy_with_y_target_with_labels.png
  tests/baseline_images/test_contrib/test_missing/test_bar/test_missingvaluesbar_pandas.png
  tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_numpy.png
  tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_numpy_with_y_targets.png
  tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas.png
  tests/baseline_images/test_contrib/test_missing/test_dispersion/test_missingvaluesdispersion_with_pandas_with_y_targets.png
  tests/test_contrib/test_missing/test_bar.py
  tests/test_contrib/test_missing/test_dispersion.py
  yellowbrick/contrib/missing/__init__.py
  yellowbrick/contrib/missing/bar.py
  yellowbrick/contrib/missing/base.py
  yellowbrick/contrib/missing/dispersion.py
  yellowbrick/features/base.py
Labels: review

#513 ClassBalance backwards compatibility warnings
  docs/api/target/class_balance.rst
  tests/test_target/test_class_balance.py
  yellowbrick/target/class_balance.py
Labels: review

#522 Repairs some of the ROCAUC tests
  tests/baseline_images/test_classifier/test_rocauc/test_multiclass_rocauc.png
  tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_classes.png
  tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_macro.png
  tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_macro_no_micro.png
  tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_micro.png
  tests/test_classifier/test_rocauc.py
Labels: review

#518 Added histogram.py under features
  tests/baseline_images/test_target/test_binning/test_balancedbinningreference.png
  tests/test_target/test_binning.py
  yellowbrick/target/__init__.py
  yellowbrick/target/binning.py
Labels: review

#528 Add recommended timeline to contributing guidelines
  CONTRIBUTING.md
Labels: review, type: documentation

#510 [MRG] Enhanced FeatureImportances for Multidimensional Coefficients
  examples/zjpoh/stacked_feature_importance.ipynb
  tests/baseline_images/test_features/test_importances/test_multi_coefs_stacked.png
  tests/test_features/test_importances.py
  yellowbrick/features/importances.py
Labels: ready

#521 JOSS paper submission and bibliography
  paper/codemeta.json
  paper/figures/classification.png
  paper/figures/clustering.png
  paper/figures/feature_analysis.png
  paper/figures/figures.py
  paper/figures/hyperparameter_tuning.png
  paper/figures/regression.png
  paper/paper.bib
  paper/paper.md
Labels: review

#534 Fixes #523, Adds probability density function to ResidualsPlot's histogram
  yellowbrick/regressor/residuals.py
Labels: review

#530 [#529] Fix argument names in K-Elbow docstring
  yellowbrick/cluster/elbow.py
Labels: review, type: documentation
