Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-06, with the labels that each got.

#426 start of gallery
  docs/gallery.rst
  docs/index.rst
Labels: in progress

#463 feat: If applied, this commit will make 'support' optional for classification report
  tests/baseline_images/test_classifier/test_classification_report/test_binary_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_multiclass_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_pandas_integration.png
  tests/baseline_images/test_classifier/test_classification_report/test_quick_method.png
  tests/baseline_images/test_classifier/test_classification_report/test_support_count_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_support_percent_class_report.png
  tests/test_classifier/test_classification_report.py
  yellowbrick/classifier/classification_report.py
Labels: review

#469 added documentation for cv_scores
  docs/api/model_selection/cv.py
  docs/api/model_selection/images/cv_scores_classifier.png
  docs/api/model_selection/images/cv_scores_regressor.png
Labels: review

#468 Updates to branch and upstream management in guide
  CONTRIBUTING.md
Labels: review, type: documentation

#471 Improving Quick Start Documentation
  docs/quickstart.rst
Labels: ready

#484 Fixes #257 - Adds datasaurus dataset to show importance of visualizing data
  yellowbrick/__init__.py
  yellowbrick/datasaurus.py
Labels: review

#486 Fix #147 Implements a lexical dispersion plot
  yellowbrick/text/__init__.py
  yellowbrick/text/dispersion.py
Labels: review

#490 Feature importances fix
  examples/rebeccabilbro/feature_importances_fix.ipynb
  examples/rebeccabilbro/logistic_regression_coef_shape_issue.ipynb
  examples/rebeccabilbro/size_param_issue.ipynb
  tests/test_features/test_importances.py
  yellowbrick/features/importances.py
Labels: review

#489 Fix #487 Create Test and docs for DispersionPlot
  docs/api/text/dispersion.py
  docs/api/text/dispersion.rst
  docs/api/text/images/dispersion_docs.png
  docs/api/text/index.rst
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_generator_input.png
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_ignore_case.png
  tests/baseline_images/test_text/test_dispersion/test_integrated_dispersionplot.png
  tests/test_text/test_dispersion.py
  yellowbrick/text/dispersion.py
Labels: review
