Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-11, with the labels that each got.

#647 Remove deprecated method from documentation
  docs/api/features/images/normalized_sampled_parallel_coordinates.png
  docs/api/features/images/parallel_coordinates.png
  docs/api/features/images/radviz.png
  docs/api/features/images/rank1d_shapiro.png
  docs/api/features/images/rank2d_covariance.png
  docs/api/features/images/rank2d_pearson.png
  docs/api/features/pcoords.py
  docs/api/features/radviz.py
  docs/api/features/rankd.py
  docs/api/regressor/alphas.py
  docs/api/regressor/images/alpha_selection.png
  docs/api/regressor/images/prediction_error.png
  docs/api/regressor/peplot.py
Labels: review, type: documentation

#652 Update documentation of the KElbowVisualizer
  docs/api/cluster/elbow.py
  docs/api/cluster/elbow.rst
  docs/api/cluster/images/calinski_harabaz.png
  docs/api/cluster/images/elbow.png
  docs/api/cluster/images/elbow_is_behind.png
Labels: type: documentation

#653 Update docs by altering inline code so that input text is formatted correctly for Dispersion Plot
  docs/api/text/dispersion.py
  docs/api/text/dispersion.rst
  docs/api/text/images/dispersion_docs.png
  docs/gallery.rst
Labels: review
