Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-08, with the labels that each got.

#533 Rocauc refactor
  examples/rebeccabilbro/rocauc_bug_fix.ipynb
  examples/rebeccabilbro/rocauc_bug_research.ipynb
  tests/baseline_images/test_classifier/test_rocauc/test_binary_decision.png
  tests/baseline_images/test_classifier/test_rocauc/test_binary_probability.png
  tests/baseline_images/test_classifier/test_rocauc/test_binary_probability_decision.png
  tests/test_classifier/test_rocauc.py
  yellowbrick/classifier/rocauc.py
Labels: review

#536 Corrects the color of the test residuals for ResidualsPlot quick method
  tests/baseline_images/test_regressor/test_residuals/test_peplot_no_lines.png
  tests/baseline_images/test_regressor/test_residuals/test_peplot_no_shared_limits.png
  tests/baseline_images/test_regressor/test_residuals/test_pred_error.png
  tests/baseline_images/test_regressor/test_residuals/test_prediction_error.png
  tests/baseline_images/test_regressor/test_residuals/test_prediction_error_pandas.png
  tests/baseline_images/test_regressor/test_residuals/test_resid_plots.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_no_histogram.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_pandas.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_quick_method.png
  yellowbrick/regressor/residuals.py
Labels: review

#538 Change name of regression-examples notebook
  examples/regression.ipynb
Labels: review, type: documentation

#540 Finish up the ROCAUC docs per issue #252
  docs/api/classifier/images/rocauc_binary.png
  docs/api/classifier/images/rocauc_multiclass.png
  docs/api/classifier/rocauc.py
  docs/api/classifier/rocauc.rst
  docs/gallery.rst
  yellowbrick/classifier/rocauc.py
Labels: review

#544 Small fix to contrib.scatter docs to update import statement
  docs/api/contrib/scatter.rst
Labels: review

#542 Fixes TSNEVisualizer title size bug
  tests/test_text/test_tsne.py
  yellowbrick/text/tsne.py
Labels: review

#545 Fixes the axes labels in the jointplot image in the docs
  docs/api/features/images/jointplot.png
  docs/api/features/images/jointplot_hex.png
  docs/api/features/index.rst
  docs/api/features/jointplot.py
Labels: review

#547 Adds preliminary documentation for CVScores visualizer
  docs/api/model_selection/cv.py
  docs/api/model_selection/cv.rst
  docs/api/model_selection/images/cross_validation.png
  docs/api/model_selection/images/cv_scores_classifier.png
  docs/api/model_selection/images/cv_scores_regressor.png
  docs/api/model_selection/index.rst
  docs/gallery.rst
  examples/rebeccabilbro/cvscores_experimentation.ipynb
  yellowbrick/model_selection/cv.py
Labels: review

#548 Adds import statement to contrib's init for easier ScatterPlot import
  yellowbrick/contrib/__init__.py
Labels: review

#554 Adds an alpha param to Scatterplot
  examples/peterespinosa/adding-scatterplot-alpha.ipynb
  tests/test_contrib/test_scatter.py
  yellowbrick/contrib/scatter.py
Labels: ready

#555 Minor updates to contrib ScatterViz tests
  tests/test_contrib/test_scatter.py
Labels: review

#559 Finishing up CVscores visualizer
  docs/api/model_selection/cross_validation.py
  docs/api/model_selection/cross_validation.rst
  docs/api/model_selection/images/cv_scores_classifier.png
  docs/api/model_selection/images/cv_scores_regressor.png
  docs/api/model_selection/index.rst
  docs/gallery.rst
  examples/rebeccabilbro/cvscores_enhancements.ipynb
  tests/baseline_images/test_model_selection/test_cross_validation/test_classifier.png
  tests/baseline_images/test_model_selection/test_cross_validation/test_pandas_integration.png
  tests/baseline_images/test_model_selection/test_cross_validation/test_quick_method.png
  tests/baseline_images/test_model_selection/test_cross_validation/test_regression.png
  tests/test_model_selection/test_cross_validation.py
  yellowbrick/model_selection/__init__.py
  yellowbrick/model_selection/cross_validation.py
Labels: review

#561 Adds Preliminary Docs and Slides for Teaching YB
  docs/about.rst
  docs/index.rst
  docs/teaching.rst
Labels: review

#562 Frequently Asked Questions documentation
  docs/faq.rst
  docs/index.rst
Labels: review

#563 Add notebook with clustering visualizer examples
  examples/clustering.ipynb
Labels: review

#532 [MRG] Feature Correlation to Dependent Variable Visualizer
  examples/zjpoh/correlated_var.ipynb
  tests/baseline_images/test_target/test_feature_correlation/test_feature_correlation_integrated_mutual_info_classification.png
  tests/baseline_images/test_target/test_feature_correlation/test_feature_correlation_integrated_mutual_info_regression.png
  tests/baseline_images/test_target/test_feature_correlation/test_feature_correlation_integrated_pearson.png
  tests/baseline_images/test_target/test_feature_correlation/test_feature_correlation_quick_method.png
  tests/test_target/test_feature_correlation.py
  yellowbrick/target/__init__.py
  yellowbrick/target/feature_correlation.py
Labels: ready

#564 Adds manual legend drawing utility
  .gitignore
  docs/api/regressor/images/residuals.png
  tests/baseline_images/test_draw/test_manual_legend.png
  tests/baseline_images/test_features/test_radviz/test_integrated_radiz_pandas_classes_features.png
  tests/baseline_images/test_features/test_radviz/test_integrated_radiz_with_pandas.png
  tests/baseline_images/test_features/test_radviz/test_radviz.png
  tests/baseline_images/test_features/test_radviz/test_radviz_alpha.png
  tests/test_draw.py
  yellowbrick/draw.py
  yellowbrick/features/manifold.py
  yellowbrick/features/pcoords.py
  yellowbrick/features/radviz.py
  yellowbrick/regressor/residuals.py
Labels: review

#565 Update import statement in examples.ipynb
  examples/examples.ipynb
Labels: review

#567 Fixes #491 unicode-decode error on Windows
  tests/dataset.py
  tests/test_text/test_dispersion.py
  tests/test_text/test_tsne.py
Labels: ready

#578 Adding interactive classifier example
  examples/jlinGG/Interactive_YB_classifiers.ipynb
Labels: ready

#575 Fix link to Baleen RSS Corpus
  docs/api/text/corpus.rst
Labels: review, type: documentation

#586 Update silhouette.py
  yellowbrick/cluster/silhouette.py
Labels: ready

#573 Adds Intercluster Distance Map visualizer
  DESCRIPTION.rst
  README.md
  docs/api/cluster/icdm.py
  docs/api/cluster/icdm.rst
  docs/api/cluster/images/icdm.png
  docs/api/cluster/index.rst
  docs/gallery.rst
  docs/index.rst
  examples/bbengfort/cluster.ipynb
  tests/baseline_images/test_cluster/test_icdm/test_affinity_tsne_no_legend.png
  tests/baseline_images/test_cluster/test_icdm/test_kmeans_mds.png
  tests/baseline_images/test_cluster/test_icdm/test_quick_method.png
  tests/test_cluster/test_icdm.py
  tests/test_utils/test_helpers.py
  yellowbrick/cluster/__init__.py
  yellowbrick/cluster/icdm.py
  yellowbrick/utils/helpers.py
Labels: review

#576 If applied this commit denotes document boundaries on Dispersion Plot viz
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_annotate_docs.png
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_generator_input.png
  tests/baseline_images/test_text/test_dispersion/test_dispersionplot_ignore_case.png
  tests/baseline_images/test_text/test_dispersion/test_integrated_dispersionplot.png
  tests/test_text/test_dispersion.py
  yellowbrick/text/dispersion.py
Labels: review

#587 Implements #537 KElbowVisualizer can accept an iterable of integers.
  tests/test_cluster/test_elbow.py
  yellowbrick/cluster/elbow.py
Labels: ready

#591 Finishes SilhouetteVisualizer docstring, completing #583
  yellowbrick/cluster/silhouette.py
Labels: review

#574 Adds alpha params to other scatterplot-based visualizers
  examples/rebeccabilbro/prediction_error_alpha.ipynb
  examples/rebeccabilbro/tsne_alpha_manual_legend.ipynb
  tests/baseline_images/test_regressor/test_residuals/test_peplot_no_shared_limits.png
  tests/baseline_images/test_regressor/test_residuals/test_prediction_error.png
  tests/baseline_images/test_regressor/test_residuals/test_prediction_error_pandas.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_no_histogram.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_pandas.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_quick_method.png
  tests/baseline_images/test_text/test_tsne/test_integrated_tsne.png
  tests/baseline_images/test_text/test_tsne/test_make_classification_tsne.png
  tests/baseline_images/test_text/test_tsne/test_make_classification_tsne_class_labels.png
  tests/baseline_images/test_text/test_tsne/test_no_target_tsne.png
  tests/baseline_images/test_text/test_tsne/test_visualizer_with_pandas.png
  tests/test_regressor/test_residuals.py
  tests/test_text/test_tsne.py
  yellowbrick/regressor/residuals.py
  yellowbrick/text/tsne.py
Labels: review

#568 [MRG] Add FeatureCorrelation to Documentation
  DESCRIPTION.rst
  README.md
  docs/api/target/feature_correlation.py
  docs/api/target/feature_correlation.rst
  docs/api/target/images/feature_correlation_mutual_info_classification.png
  docs/api/target/images/feature_correlation_mutual_info_regression.png
  docs/api/target/images/feature_correlation_pearson.png
  docs/api/target/index.rst
  docs/gallery.rst
  examples/zjpoh/correlated_var.ipynb
  yellowbrick/target/feature_correlation.py
Labels: ready
