Repository DistrictDataLabs/yellowbrick, pull requests merged in 2018-03, with the labels that each got.

#309 Features refactor
  examples/pbs929/features-pipeline.ipynb
  yellowbrick/features/__init__.py
  yellowbrick/features/base.py
  yellowbrick/features/pca.py
  yellowbrick/features/radviz.py
  yellowbrick/features/rankd.py
  yellowbrick/features/scatter.py
Labels: ready

#238 add decomposition explained variance visualizer
  yellowbrick/features/decomposition.py
Labels: ready

#327 Fixes to the resolve colors function
  tests/test_style/test_colors.py
  tests/test_style/test_palettes.py
  yellowbrick/classifier/boundaries.py
  yellowbrick/classifier/threshold.py
  yellowbrick/features/pcoords.py
  yellowbrick/features/radviz.py
  yellowbrick/features/scatter.py
  yellowbrick/style/colors.py
  yellowbrick/style/palettes.py
Labels: review

#332 Rankd Basic Tests
  tests/baseline_images/test_features/test_rankd/test_integrated_rankd1.png
  tests/baseline_images/test_features/test_rankd/test_integrated_rankd2.png
  tests/baseline_images/test_features/test_rankd/test_rankd1.png
  tests/baseline_images/test_features/test_rankd/test_rankd2.png
  tests/test_features/test_rankd.py
  tests/test_features/tests/actual_images/test_features/test_rankd/test_integrated_rankd1.png
  tests/test_features/tests/actual_images/test_features/test_rankd/test_rankd1.png
Labels: review

#321 Class Balance Heat Map Visualizer
  examples/lwgray/ClassPredictionError.ipynb
  tests/test_classifier/test_class_prediction_error.py
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_multiclass_rocauc.png
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_classes.png
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_curves.png
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_macro.png
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_macro_no_micro.png
  tests/test_classifier/tests/baseline_images/test_classifier/test_rocauc/test_rocauc_no_micro.png
  yellowbrick/classifier/__init__.py
  yellowbrick/classifier/class_balance.py
Labels: review

#330 Documentation updates
  README.md
  docs/about.rst
  docs/api/anscombe.rst
  docs/api/datasets.rst
  docs/api/index.rst
  docs/api/palettes.rst
  docs/changelog.rst
  docs/evaluation.rst
  docs/quickstart.rst
Labels: review

#336 Minor Readme Update
  README.md
Labels: review

#338 Add pandas test to radviz
  tests/baseline_images/test_features/test_radviz/test_integrated_radiz_with_pandas.png
  tests/baseline_images/test_features/test_radviz/test_integrated_radiz_with_pandas_with_classes.png
  tests/baseline_images/test_features/test_radviz/test_radviz.png
  tests/test_features/test_radviz.py
Labels: review

#347 If applied this commit: Creates docs for ClassPredictError Visualizer
  docs/api/classifier/class_prediction_error.py
  docs/api/classifier/class_prediction_error.rst
  docs/api/classifier/images/class_prediction_error.png
Labels: review

#333 Fix tSNE bugs from numpy 1.13
  docs/api/text/images/tsne_all_docs.png
  docs/api/text/images/tsne_kmeans.png
  docs/api/text/images/tsne_limit_classes.png
  docs/api/text/images/tsne_no_labels.png
  docs/api/text/tsne.py
  docs/api/text/tsne.rst
  requirements.txt
  tests/baseline_images/test_text/test_tsne/test_integrated_tsne.png
  tests/baseline_images/test_text/test_tsne/test_make_classification_tsne.png
  tests/baseline_images/test_text/test_tsne/test_make_classification_tsne_class_labels.png
  tests/baseline_images/test_text/test_tsne/test_no_target_tsne.png
  tests/baseline_images/test_text/test_tsne/test_visualizer_with_pandas.png
  tests/requirements.txt
  tests/test_text/test_tsne.py
  yellowbrick/text/tsne.py
Labels: review

#342 ClassPredictionError Tests
  tests/baseline_images/test_classifier/test_class_prediction_error/test_class_prediction_error_quickmethod.png
  tests/baseline_images/test_classifier/test_class_prediction_error/test_integration_class_prediction_error_.png
  tests/test_classifier/test_class_prediction_error.py
  yellowbrick/classifier/class_balance.py
Labels: review

#343 Removes font size hardcode from confusion matrix
  docs/api/classifier/images/confusion_matrix.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_class_filter_eg_zoom_in.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_confusion_matrix.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_extra_classes.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_fontsize.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_inverse_mapping.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_no_classes_provided.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_one_class.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_pandas_integration.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_percent_mode.png
  tests/test_classifier/test_confusion_matrix.py
  yellowbrick/__init__.py
  yellowbrick/classifier/confusion_matrix.py
  yellowbrick/classifier/rocauc.py
Labels: review

#348 Updates ClassificationReport to use pcolormesh
  docs/api/classifier/classification_report.py
  docs/api/classifier/images/classification_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_binary_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_multiclass_class_report.png
  tests/baseline_images/test_classifier/test_classification_report/test_pandas_integration.png
  tests/baseline_images/test_classifier/test_classification_report/test_quick_method.png
  tests/baseline_images/test_classifier/test_confusion_matrix/test_quick_method.png
  tests/test_classifier/test_classification_report.py
  tests/test_classifier/test_confusion_matrix.py
  yellowbrick/classifier/classification_report.py
  yellowbrick/classifier/confusion_matrix.py
Labels: review

#346 Add deprecation warnings on scatterviz and boundariesvisualizer
  tests/test_classifier/test_boundaries.py
  tests/test_features/test_scatter.py
  yellowbrick/classifier/boundaries.py
  yellowbrick/features/scatter.py
Labels: review

#352 Update images in generated docs
  docs/api/classifier/images/class_balance.png
  docs/api/classifier/images/class_prediction_error.png
  docs/api/classifier/images/class_prediction_error_credit.png
  docs/api/classifier/images/classification_report.png
  docs/api/classifier/images/confusion_matrix.png
  docs/api/classifier/images/rocauc.png
  docs/api/classifier/images/thresholdviz.png
  docs/api/cluster/images/elbow.png
  docs/api/cluster/images/silhouette.png
  docs/api/features/images/feature_importances.png
  docs/api/features/images/feature_importances_coef.png
  docs/api/features/images/jointplot.png
  docs/api/features/images/jointplot_hex.png
  docs/api/features/images/normalized_sampled_parallel_coordinates.png
  docs/api/features/images/parallel_coordinates.png
  docs/api/features/images/pca_projection_2d.png
  docs/api/features/images/pca_projection_3d.png
  docs/api/features/images/radviz.png
  docs/api/features/images/rank1d_shapiro.png
  docs/api/features/images/rank2d_covariance.png
  docs/api/features/images/rank2d_pearson.png
  docs/api/features/images/scatter.png
  docs/api/images/anscombe.png
  docs/api/regressor/images/prediction_error.png
  docs/api/regressor/images/residuals.png
  docs/api/text/corpus.rst
  docs/api/text/images/freqdist_cooking.png
  docs/api/text/images/freqdist_corpus.png
  docs/api/text/images/freqdist_gaming.png
  docs/api/text/images/freqdist_stopwords.png
  docs/api/text/images/tsne_all_docs.png
  docs/api/text/images/tsne_kmeans.png
  docs/api/text/images/tsne_no_labels.png
Labels: review

#355 Make sklearn classification dataset for Class Prediction Error Tests #342
  tests/baseline_images/test_classifier/test_class_prediction_error/test_class_prediction_error_quickmethod.png
  tests/baseline_images/test_classifier/test_class_prediction_error/test_integration_class_prediction_error_.png
  tests/test_classifier/test_class_prediction_error.py
Labels: review

#350 Fix documentation: Add import statements to documentation for individual visualizers
  docs/api/classifier/class_balance.rst
  docs/api/classifier/class_prediction_error.rst
  docs/api/classifier/classification_report.rst
  docs/api/classifier/confusion_matrix.rst
  docs/api/classifier/rocauc.rst
  docs/api/classifier/threshold.rst
  docs/api/cluster/elbow.rst
  docs/api/cluster/silhouette.rst
  docs/api/features/importances.rst
  docs/api/features/pca.rst
  docs/api/features/pcoords.rst
  docs/api/features/radviz.rst
  docs/api/features/rankd.rst
  docs/api/features/scatter.rst
  docs/api/regressor/alphas.rst
  docs/api/regressor/peplot.rst
  docs/api/regressor/residuals.rst
  docs/api/text/corpus.rst
  docs/api/text/freqdist.rst
  docs/api/text/tsne.rst
Labels: review

#176 WIP: Basic version of the multiplevisualizer base class
  examples/nealhumphrey/MultipleVisualizerExample.ipynb
  tests/test_base.py
  yellowbrick/base.py
Labels: in progress, type: feature, type: technical debt

#356 Remove hard-coded test data I left by accident
  tests/test_classifier/test_class_prediction_error.py
Labels: review

#357 Adds RandomVisualizer and updates VisualizerGrid tests
  tests/base.py
  tests/baseline_images/test_base/test_draw_visualizer_grid.png
  tests/baseline_images/test_base/test_draw_with_cols.png
  tests/baseline_images/test_base/test_draw_with_rows.png
  tests/random.py
  tests/test_base.py
  yellowbrick/base.py
Labels: review

#358 Modifies Scoring Mechanism for Regressor Visualizers
  docs/api/regressor/alphas.py
  docs/api/regressor/alphas.rst
  docs/api/regressor/images/alpha_selection.png
  docs/api/regressor/images/prediction_error.png
  docs/api/regressor/images/residuals.png
  tests/baseline_images/test_regressor/test_alphas/test_similar_image.png
  tests/baseline_images/test_regressor/test_residuals/test_pred_error_integration.png
  tests/baseline_images/test_regressor/test_residuals/test_pred_error_integration_pandas.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_integration.png
  tests/baseline_images/test_regressor/test_residuals/test_residuals_plot_integration_pandas.png
  tests/conftest.py
  tests/dataset.py
  tests/test_classifier/test_confusion_matrix.py
  tests/test_regressor/test_alphas.py
  tests/test_regressor/test_residuals.py
  yellowbrick/base.py
  yellowbrick/regressor/alphas.py
  yellowbrick/regressor/base.py
  yellowbrick/regressor/residuals.py
Labels: review

#364 WIP: Updates to discrimination threshold visualizer.
  DESCRIPTION.rst
  README.md
  docs/api/classifier/images/churn_discrimination_threshold.png
  docs/api/classifier/images/spam_discrimination_threshold.png
  docs/api/classifier/images/thresholdviz.png
  docs/api/classifier/index.rst
  docs/api/classifier/threshold.py
  docs/api/classifier/threshold.rst
  docs/api/datasets.rst
  docs/index.rst
  examples/download.py
  tests/baseline_images/test_classifier/test_threshold/test_binary_discrimination_threshold.png
  tests/baseline_images/test_classifier/test_threshold/test_binary_discrimination_threshold_alt_args.png
  tests/baseline_images/test_classifier/test_threshold/test_pandas_integration.png
  tests/baseline_images/test_classifier/test_threshold/test_quick_method.png
  tests/baseline_images/test_classifier/test_threshold/test_threshold_viz.png
  tests/baseline_images/test_classifier/test_threshold/test_threshold_viz_quick_method_read_data.png
  tests/baseline_images/test_classifier/test_threshold/test_threshold_viz_read_data.png
  tests/dataset.py
  tests/test_classifier/conftest.py
  tests/test_classifier/test_classification_report.py
  tests/test_classifier/test_threshold.py
  tests/test_utils/test_helpers.py
  tests/test_utils/test_types.py
  yellowbrick/classifier/__init__.py
  yellowbrick/classifier/threshold.py
  yellowbrick/download.py
  yellowbrick/utils/helpers.py
  yellowbrick/utils/types.py
Labels: review

#371 Updates the distortion score metric to handle sparse matrices
  tests/test_cluster/test_elbow.py
  yellowbrick/cluster/elbow.py
Labels: review

#376 Adding yellowbrick.contrib to main package, tests and docs
  docs/api/contrib/boundaries.py
  docs/api/contrib/boundaries.rst
  docs/api/contrib/images/knn_decisionviz.png
  docs/api/contrib/images/svc_decisionviz.png
  docs/api/contrib/index.rst
  docs/api/index.rst
  tests/baseline_images/test_contrib/test_classifier/test_boundaries/test_integrated_plot_numpy_named_arrays.png
  tests/baseline_images/test_contrib/test_classifier/test_boundaries/test_real_data_set_viz.png
  tests/test_contrib/test_classifier/test_boundaries.py
  yellowbrick/classifier/__init__.py
  yellowbrick/classifier/boundaries.py
  yellowbrick/contrib/__init__.py
  yellowbrick/contrib/classifier/__init__.py
  yellowbrick/contrib/classifier/boundaries.py
Labels: review
