Repository DistrictDataLabs/yellowbrick, pull requests merged in 2019-02, with the labels that each got.

#712 Fix errors related to release of pytest 4.2
  requirements.txt
  setup.cfg
  tests/conftest.py
  tests/requirements.txt
Labels: review

#713 Documents the yellowbrick.download script.
  README.md
  docs/contributing/developing_visualizers.rst
Labels: review

#446 Auto-generate Images for Documentation
  docs/api/cluster/elbow.py
  docs/api/cluster/elbow.rst
  docs/api/cluster/images/calinski_harabaz.png
  docs/api/features/images/feature_importances_coef.png
  docs/api/features/images/feature_importances_stacked.png
  docs/api/features/importances.py
  docs/api/features/importances.rst
  docs/conf.py
  docs/make.bat
  docs/requirements.txt
  requirements.txt
Labels: review

#695 Update code to import data in regression notebook
  examples/regression.ipynb
Labels: review, type: example

#719 Adds plot directives to quickstart
  docs/images/quickstart/bikeshare_ols_residuals.png
  docs/images/quickstart/bikeshare_rank2d.png
  docs/images/quickstart/bikeshare_ridge_alphas.png
  docs/images/quickstart/bikeshare_ridge_prediction_error.png
  docs/images/quickstart/temp_feelslike_jointplot.png
  docs/quickstart.rst
  examples/walkthrough.ipynb
  tests/baseline_images/test_features/test_jointplot/test_jointplot_has_no_errors.png
  tests/baseline_images/test_features/test_jointplot/test_jointplot_integrated_has_no_errors.png
  tests/test_base.py
  yellowbrick/base.py
  yellowbrick/features/jointplot.py
  yellowbrick/features/rankd.py
Labels: review

#720 Streamlining the README
  README.md
  docs/images/readme_classifiers.png
  docs/images/readme_clusterers.png
  docs/images/readme_imgs.py
  docs/images/readme_regressors.png
Labels: review

#726 Adds hotfix tag and summary to changelog in docs
  docs/changelog.rst
Labels: review

#721 Refresh the JointPlot Visualizer for ML
  docs/quickstart.rst
  tests/baseline_images/test_features/test_jointplot/test_columns_double_index_continuous_y.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_index_continuous_y_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_index_discrete_y.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_index_discrete_y_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_int_index_numpy_no_y.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_int_index_numpy_no_y_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_str_index_pandas_no_y.png
  tests/baseline_images/test_features/test_jointplot/test_columns_double_str_index_pandas_no_y_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_none_x.png
  tests/baseline_images/test_features/test_jointplot/test_columns_none_x_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_none_x_y.png
  tests/baseline_images/test_features/test_jointplot/test_columns_none_x_y_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_single_int_index_numpy.png
  tests/baseline_images/test_features/test_jointplot/test_columns_single_int_index_numpy_hist.png
  tests/baseline_images/test_features/test_jointplot/test_columns_single_str_index_pandas.png
  tests/baseline_images/test_features/test_jointplot/test_columns_single_str_index_pandas_hist.png
  tests/baseline_images/test_features/test_jointplot/test_jointplot_has_no_errors.png
  tests/baseline_images/test_features/test_jointplot/test_jointplot_integrated_has_no_errors.png
  tests/test_features/test_jointplot.py
  yellowbrick/features/__init__.py
  yellowbrick/features/jointplot.py
Labels: review

#731 Tips and conventions for contributors and reviewers
  docs/contributing/advanced_development_topics.rst
  docs/contributing/developing_visualizers.rst
  docs/contributing/getting_started.rst
Labels: review

#733 Implement plot directive for ClassificationReport docs
  docs/api/classifier/classification_report.py
  docs/api/classifier/classification_report.rst
  docs/contributing/getting_started.rst
Labels: review

#732 Make gallery independent of plot directives
  README.md
  docs/changelog.rst
  docs/conf.py
  docs/gallery.py
  docs/gallery.rst
  docs/images/favicon.ico
  docs/images/gallery/alpha_selection.png
  docs/images/gallery/balanced_binning_reference.png
  docs/images/gallery/class_balance.png
  docs/images/gallery/class_prediction_error.png
  docs/images/gallery/classification_report.png
  docs/images/gallery/concrete_isomap_manifold.png
  docs/images/gallery/concrete_tsne_manifold.png
  docs/images/gallery/confusion_matrix_digits.png
  docs/images/gallery/confusion_matrix_iris.png
  docs/images/gallery/corpus_tsne.png
  docs/images/gallery/cv_scores.png
  docs/images/gallery/decision_boundaries.png
  docs/images/gallery/discrimination_threshold.png
  docs/images/gallery/dispersion.png
  docs/images/gallery/elbow.png
  docs/images/gallery/feature_correlation.png
  docs/images/gallery/feature_importances.png
  docs/images/gallery/freqdist.png
  docs/images/gallery/icdm.png
  docs/images/gallery/jointplot.png
  docs/images/gallery/learning_curve.png
  docs/images/gallery/occupancy_tsne_manifold.png
  docs/images/gallery/parallel_coordinates.png
  docs/images/gallery/pca_projection_3d.png
  docs/images/gallery/precision_recall_binary.png
  docs/images/gallery/precision_recall_multiclass.png
  docs/images/gallery/prediction_error.png
  docs/images/gallery/radviz.png
  docs/images/gallery/rank1d_shapiro.png
  docs/images/gallery/rank2d_covariance.png
  docs/images/gallery/residuals.png
  docs/images/gallery/rfecv_sklearn_example.png
  docs/images/gallery/rocauc_binary.png
  docs/images/gallery/rocauc_multiclass.png
  docs/images/gallery/scatter.png
  docs/images/gallery/silhouette.png
  docs/images/gallery/validation_curve.png
  docs/images/matplotlib/anatomy.png
  docs/images/matplotlib/pbpython_example.png
  docs/images/matplotlib/single.png
  docs/images/readme/classifiers.png
  docs/images/readme/clusterers.png
  docs/images/readme/readme_imgs.py
  docs/images/readme/regressors.png
  docs/matplotlib.rst
  yellowbrick/target/binning.py
Labels: review

#736 Create READMEs for the docs and tests
  docs/README.md
  docs/api/features/jointplot.rst
  docs/quickstart.rst
  tests/README.md
  yellowbrick/features/jointplot.py
Labels: review

#743 Workaround for AppVeyor Miniconda3 Tests
  .appveyor.yml
  .travis.yml
  tests/requirements.txt
Labels: review

#737 Implement plot directive for Class_prediction_error (towards #687)
  docs/api/classifier/class_prediction_error.py
  docs/api/classifier/class_prediction_error.rst
  docs/api/classifier/images/class_prediction_error.png
  docs/api/classifier/images/class_prediction_error_credit.png
Labels: review

#740 Implement plot directive for ROCAUC
  docs/api/classifier/images/rocauc.png
  docs/api/classifier/images/rocauc_binary.png
  docs/api/classifier/images/rocauc_multiclass.png
  docs/api/classifier/rocauc.py
  docs/api/classifier/rocauc.rst
Labels: review

#729 Alter ParallelCoordinates docs to include plot:: directives
  docs/api/cluster/elbow.rst
  docs/api/features/images/fast_vs_slow_parallel_coordinates.png
  docs/api/features/images/normalized_sampled_parallel_coordinates.png
  docs/api/features/importances.rst
  docs/api/features/pcoords.py
  docs/api/features/pcoords.rst
  docs/api/features/pcoords_benchmark.py
  docs/api/text/dispersion.rst
Labels: review

#688 [MRG] Bug fix for PR curve multiclasses labels
  tests/baseline_images/test_classifier/test_prcurve/test_multiclass_probability_with_class_labels.png
  tests/test_classifier/test_prcurve.py
  yellowbrick/classifier/prcurve.py
Labels: ready

#750 Changelog Updates
  docs/changelog.rst
  tests/baseline_images/test_classifier/test_prcurve/test_multiclass_probability_with_class_labels.png
  tests/baseline_images/test_classifier/test_prcurve/test_quick_method_with_test_set.png
  tests/test_classifier/test_prcurve.py
Labels: review

#742 Implement new plot directive for clustering visualizers [Issue #687]
  docs/api/cluster/elbow.rst
  docs/api/cluster/icdm.py
  docs/api/cluster/icdm.rst
  docs/api/cluster/images/elbow.png
  docs/api/cluster/images/icdm.png
  docs/api/cluster/images/silhouette.png
  docs/api/cluster/silhouette.py
  docs/api/cluster/silhouette.rst
Labels: type: documentation

#747 Implement Plot Directive for ConfusionMatrix, PrecisionRecall and Decisionviz
  docs/api/classifier/class_prediction_error.rst
  docs/api/classifier/confusion_matrix.py
  docs/api/classifier/confusion_matrix.rst
  docs/api/classifier/images/binary_precision_recall.png
  docs/api/classifier/images/confusion_matrix_digits.png
  docs/api/classifier/images/confusion_matrix_iris.png
  docs/api/classifier/images/multiclass_precision_recall.png
  docs/api/classifier/images/multiclass_precision_recall_full.png
  docs/api/classifier/prcurve.py
  docs/api/classifier/prcurve.rst
  docs/api/classifier/rocauc.rst
  docs/api/contrib/boundaries.py
  docs/api/contrib/boundaries.rst
  docs/api/contrib/images/knn_decisionviz.png
  docs/api/contrib/images/svc_decisionviz.png
Labels: review

#756 Minor edits to learning_curve.rst
  docs/api/model_selection/learning_curve.rst
Labels: ready

#758 Implement plot directive for RadViz documentation
  docs/api/features/images/radviz.png
  docs/api/features/radviz.py
  docs/api/features/radviz.rst
Labels: review, type: documentation

#752 Implement Discrimination threshold plot directive
  docs/api/classifier/class_prediction_error.rst
  docs/api/classifier/classification_report.rst
  docs/api/classifier/images/churn_discrimination_threshold.png
  docs/api/classifier/images/classification_report.png
  docs/api/classifier/images/spam_discrimination_threshold.png
  docs/api/classifier/rocauc.rst
  docs/api/classifier/threshold.py
  docs/api/classifier/threshold.rst
  docs/api/features/images/parallel_coordinates.png
  docs/api/features/pcoords.rst
  docs/api/text/dispersion.rst
  docs/api/text/images/dispersion_docs.png
Labels: review, type: documentation

#748 Adds plot directive to validation curves documentation
  docs/api/features/images/feature_importances.png
  docs/api/features/importances.rst
  docs/api/model_selection/images/validation_curve_classifier_knn.png
  docs/api/model_selection/images/validation_curve_classifier_svc.png
  docs/api/model_selection/images/validation_curve_regressor.png
  docs/api/model_selection/images/validation_curve_sklearn_example.png
  docs/api/model_selection/validation_curve.py
  docs/api/model_selection/validation_curve.rst
Labels: review

#757 Deprecate Python 2
  .appveyor.yml
  .travis.yml
  docs/changelog.rst
  requirements.txt
  setup.cfg
  tests/requirements.txt
  tests/test_base.py
  tests/test_classifier/test_confusion_matrix.py
  tests/test_classifier/test_threshold.py
  tests/test_contrib/test_classifier/test_boundaries.py
  tests/test_contrib/test_scatter.py
  tests/test_datasets/test_loaders.py
  tests/test_datasets/test_path.py
  tests/test_features/test_importances.py
  tests/test_features/test_jointplot.py
  tests/test_features/test_manifold.py
  tests/test_features/test_rankd.py
  tests/test_features/test_rfecv.py
  tests/test_meta.py
  tests/test_model_selection/test_cross_validation.py
  tests/test_model_selection/test_learning_curve.py
  tests/test_model_selection/test_validation_curve.py
  tests/test_pipeline.py
  tests/test_regressor/test_residuals.py
  tests/test_text/test_tsne.py
  tests/test_text/test_umap.py
  tests/test_utils/test_timer.py
  tests/test_utils/test_wrapper.py
  yellowbrick/classifier/classification_report.py
  yellowbrick/classifier/threshold.py
  yellowbrick/datasets/base.py
  yellowbrick/datasets/download.py
  yellowbrick/features/manifold.py
  yellowbrick/features/pcoords.py
  yellowbrick/style/colors.py
  yellowbrick/style/palettes.py
  yellowbrick/utils/helpers.py
  yellowbrick/utils/timer.py
Labels: review

#766 Forces datasets loader to forbid pickle
  yellowbrick/datasets/base.py
  yellowbrick/datasets/manifest.json
Labels: review

#759 Add plot directive to Rank1D and Rank2D docs
  docs/api/features/images/rank1d_shapiro.png
  docs/api/features/images/rank2d_covariance.png
  docs/api/features/images/rank2d_pearson.png
  docs/api/features/rankd.py
  docs/api/features/rankd.rst
Labels: review, type: documentation

#760 Add plot directive to ScatterVisualizer docs
  docs/api/contrib/images/scatter.png
  docs/api/contrib/scatter.py
  docs/api/contrib/scatter.rst
Labels: review, type: documentation

#769 Fixed incorrect link to teaching with YB slidedeck
  docs/teaching.rst
Labels: review, type: documentation

#767 Attempt to get CI notifications working
  .appveyor.yml
  .travis.yml
Labels: review

#768 Reboot of the PosTag visualizer
  docs/api/text/index.rst
  docs/api/text/postag.rst
  docs/changelog.rst
  docs/gallery.py
  docs/gallery.rst
  docs/images/gallery/postag.png
  docs/index.rst
  tests/baseline_images/test_text/test_postag/test_quick_method.png
  tests/baseline_images/test_text/test_postag/test_spacy_tagged.png
  tests/baseline_images/test_text/test_postag/test_word_tagged.png
  tests/baseline_images/test_text/test_postag/test_wordpunct_tagged.png
  tests/requirements.txt
  tests/test_text/test_postag.py
  yellowbrick/text/postag.py
Labels: review
