Repository DistrictDataLabs/yellowbrick, pull requests merged in 2019-03, with the labels that each got.

#775 Added plot directive to CVScores docs
  docs/api/model_selection/cross_validation.py
  docs/api/model_selection/cross_validation.rst
  docs/api/model_selection/images/cv_scores_classifier.png
  docs/api/model_selection/images/cv_scores_regressor.png
Labels: review, type: documentation

#777 Added plot directive for all target visualizers
  docs/api/target/binning.py
  docs/api/target/binning.rst
  docs/api/target/class_balance.py
  docs/api/target/class_balance.rst
  docs/api/target/feature_correlation.py
  docs/api/target/feature_correlation.rst
  docs/api/target/images/balanced_binning_reference.png
  docs/api/target/images/class_balance.png
  docs/api/target/images/class_balance_compare.png
  docs/api/target/images/feature_correlation_mutual_info_classification.png
  docs/api/target/images/feature_correlation_mutual_info_regression.png
  docs/api/target/images/feature_correlation_pearson.png
Labels: review

#780 Add plot directive to LearningCurve documentation.
  docs/api/model_selection/images/learning_curve_classifier.png
  docs/api/model_selection/images/learning_curve_clusterer.png
  docs/api/model_selection/images/learning_curve_regressor.png
  docs/api/model_selection/learning_curve.py
  docs/api/model_selection/learning_curve.rst
  tests/requirements.txt
Labels: ready

#755 Changed labels to y vector,passed labels as list
  docs/api/text/tsne.rst
Labels: ready

#782 Added plot directive for AlphaSelection
  docs/api/regressor/alphas.py
  docs/api/regressor/alphas.rst
  docs/api/regressor/images/alpha_selection.png
Labels: review

#786 Add plot directive to Residuals documentation.
  docs/api/regressor/images/residuals.png
  docs/api/regressor/images/residuals_no_hist.png
  docs/api/regressor/residuals.py
  docs/api/regressor/residuals.rst
Labels: ready

#787 Add plot directive to PredictionError (peplot) documentation.
  docs/api/regressor/images/prediction_error.png
  docs/api/regressor/peplot.py
  docs/api/regressor/peplot.rst
Labels: ready

#794 JOSS paper citation
  README.md
  docs/about.rst
Labels: review

#800 Updated docs to remove reference of minabs scale for ParallelCoordina…
  docs/api/features/pcoords.rst
Labels: ready
