Repository DistrictDataLabs/yellowbrick, pull requests merged in 2019-04, with the labels that each got.

#776 Addresses Issue #741 - [elbow visualizer] Error in distortion score calculation #762
  docs/README.md
  docs/images/gallery/elbow.png
  tests/baseline_images/test_cluster/test_elbow/test_calinski_harabaz_metric.png
  tests/baseline_images/test_cluster/test_elbow/test_distortion_metric.png
  tests/baseline_images/test_cluster/test_elbow/test_integrated_kmeans_elbow.png
  tests/baseline_images/test_cluster/test_elbow/test_integrated_mini_batch_kmeans_elbow.png
  tests/baseline_images/test_cluster/test_elbow/test_silhouette_metric.png
  tests/baseline_images/test_cluster/test_elbow/test_timings.png
  tests/test_cluster/test_elbow.py
  yellowbrick/cluster/elbow.py
Labels: review

#796 New example notebook comparing tsne and umap
  examples/Sangarshanan/comparing_corpus_visualizers.ipynb
Labels: ready

#805 Added normalization technique 'maxabs' reference to ParallelCoordinates documentation (DistrictDataLabs #797)
  docs/api/features/pcoords.rst
Labels: ready

#783 [MRG] Uses approx to compare float in test_elbow
  tests/test_cluster/test_elbow.py
Labels: ready

#806 Addressing issue #590:Adding train alpha and test alpha to residual
  tests/test_regressor/test_residuals.py
  yellowbrick/regressor/residuals.py
Labels: ready

#810 New PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: review

#779 Adds frequency sort feature to PosTagVisualizer (#771)
  tests/baseline_images/test_text/test_postag/test_frequency_mode.png
  tests/test_text/test_postag.py
  yellowbrick/text/postag.py
Labels: ready

#814 Updates FreqDist docs with plot directive and datasets module
  docs/api/text/freqdist.py
  docs/api/text/freqdist.rst
  docs/api/text/images/freqdist_cooking.png
  docs/api/text/images/freqdist_corpus.png
  docs/api/text/images/freqdist_gaming.png
  docs/api/text/images/freqdist_stopwords.png
Labels: review

#811 Addressing issue #589: Adding alpha params to PCA
  tests/baseline_images/test_features/test_pca/test_biplot_2d.png
  tests/baseline_images/test_features/test_pca/test_biplot_3d.png
  tests/baseline_images/test_features/test_pca/test_pca_decomposition_quick_method.png
  tests/baseline_images/test_features/test_pca/test_scale_false_2d.png
  tests/baseline_images/test_features/test_pca/test_scale_false_3d.png
  tests/baseline_images/test_features/test_pca/test_scale_true_2d.png
  tests/baseline_images/test_features/test_pca/test_scale_true_3d.png
  tests/test_features/test_pca.py
  yellowbrick/features/pca.py
Labels: ready

#815 Updates TSNE docs with plot directive and datasets module
  docs/api/text/images/tsne_all_docs.png
  docs/api/text/images/tsne_kmeans.png
  docs/api/text/images/tsne_no_labels.png
  docs/api/text/tsne.py
  docs/api/text/tsne.rst
Labels: type: documentation

#818 Updates model selection tutorial with new datasets module
  .appveyor.yml
  docs/images/tutorial/modelselect_bagging_classifier.png
  docs/images/tutorial/modelselect_extra_trees_classifier.png
  docs/images/tutorial/modelselect_kneighbors_classifier.png
  docs/images/tutorial/modelselect_linear_svc.png
  docs/images/tutorial/modelselect_logistic_regression.png
  docs/images/tutorial/modelselect_logistic_regression_cv.png
  docs/images/tutorial/modelselect_nu_svc.png
  docs/images/tutorial/modelselect_random_forest_classifier.png
  docs/images/tutorial/modelselect_sgd_classifier.png
  docs/images/tutorial/modelselect_svc.png
  docs/tutorial.py
  docs/tutorial.rst
Labels: review

#821 Figures and Axes
  docs/api/figures.rst
  docs/api/index.rst
  docs/matplotlib.rst
Labels: review

#819 Update about page with affiliations
  docs/about.rst
Labels: review

#816 Updates UMAP docs with plot directive and datasets module
  docs/api/text/images/umap_all_docs_cosine.png
  docs/api/text/images/umap_all_docs_euclidean.png
  docs/api/text/images/umap_kmeans.png
  docs/api/text/images/umap_no_labels.png
  docs/api/text/umap_vis.py
  docs/api/text/umap_vis.rst
Labels: review, type: documentation

#827 Governance Document
  docs/governance.rst
  docs/index.rst
Labels: type: documentation, type: task
