Repository DistrictDataLabs/yellowbrick, pull requests merged in 2019-05, with the labels that each got.

#825 Updates example datasets page in Yellowbrick docs
  docs/api/datasets.rst
Labels: review

#832 replaced with valid conda envs url
  docs/contributing/getting_started.rst
Labels: ready

#836 makes documentation index page more concise
  docs/index.rst
Labels: ready

#770 Fixes Label cutoff in saved images of PosTag and ConfusionMatrix Viz
  docs/images/gallery/confusion_matrix_digits.png
  docs/images/gallery/confusion_matrix_iris.png
  docs/images/gallery/postag.png
  yellowbrick/classifier/confusion_matrix.py
  yellowbrick/text/postag.py
Labels: review

#848 Governance Amendment: Mentor-Contributor
  docs/governance.rst
Labels: review, type: documentation

#851 Doc updates to address waffle, PR procedure, and NLTK reference
  CONTRIBUTING.md
  docs/contributing/getting_started.rst
  docs/quickstart.rst
Labels: review

#839 Add legend for silhouette score
  docs/changelog.rst
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_kmeans_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_mini_batch_kmeans_silhouette.png
  tests/test_cluster/test_silhouette.py
  yellowbrick/cluster/silhouette.py
Labels: ready

#838 Change example code to use TimeSeriesSplit
  docs/api/classifier/classification_report.rst
  docs/api/classifier/rocauc.rst
  docs/api/target/class_balance.rst
Labels: ready

#833 Move silhouette cluster labels to the y-axis
  docs/changelog.rst
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_kmeans_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_mini_batch_kmeans_silhouette.png
  yellowbrick/cluster/silhouette.py
Labels: ready

#837 Add color customization to SilhouetteVisualizer
  docs/changelog.rst
  tests/baseline_images/test_cluster/test_silhouette/test_colormap_as_colors_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_colormap_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_colors_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_kmeans_silhouette.png
  tests/baseline_images/test_cluster/test_silhouette/test_integrated_mini_batch_kmeans_silhouette.png
  tests/test_cluster/test_silhouette.py
  yellowbrick/cluster/silhouette.py
  yellowbrick/style/colors.py
Labels: ready
